Repository QuasarApp/Qt-Secret, pull requests merged in 2019-06, with the labels that each got.

#8 Dev
  Qt-Secret.pro
  src/Qt-RSA/qrsaencryption.cpp
  src/Qt-RSA/qrsaencryption.h
  src/Qt-Secret.pri
  src/Qt-Secret.pro
Labels: bug, enhancement

#11 added new tests for sign message
  test.pri
  tests/main.cpp
Labels: bug

#13 added static methods, added limit on a key pairs generation
  .github/FUNDING.yml
  src/Qt-RSA/qrsaencryption.cpp
  src/Qt-RSA/qrsaencryption.h
  tests/main.cpp
Labels: bug

#14 Dev
  src/Qt-RSA/qrsaencryption.cpp
  src/Qt-RSA/qrsaencryption.h
  tests/main.cpp
Labels: bug

#17 Version1.1
  Qt-Secret.pro
  src/Qt-RSA/qrsaencryption.cpp
Labels: enhancement
